import { registerComponent } from "@src/core";
import { AddUserToChatForm } from "@src/components/add-user-to-chat-form/AddUserToChatForm";
import { AuthForm } from "@src/components/auth-form/AuthForm";
import { CreateChatForm } from "@src/components/create-chat-form/CreateChatForm";
import { AuthLayout } from "@src/components/layout/AuthLayout/AuthLayout";
import { DialogLayout } from "@src/components/layout/DialogLayout/DialogLayout";
import { DialogHeader } from "@src/components/layout/DialogLayout/components/DialogHeader/DialogHeader";
import { MessageForm } from "@src/components/message-form/MessageForm";
import { ProfileAvatar } from "@src/components/profile-avatar/ProfileAvatar";
import { ProfileLayout } from "@src/components/layout/ProfileLayout/ProfileLayout";
import { RemoveUserFromChatForm } from "@src/components/remove-user-from-chat-form/RemoveUserFromChatForm";
import { ServiceLayout } from "@src/components/layout/ServiceLayout/ServiceLayout";
import { SidebarLayout } from "@src/components/layout/SidebarLayout/SidebarLayout";
import { ProfileActions } from "@src/components/profile-actions/ProfileActions";
import { ProfileDetails } from "@src/components/profile-details/ProfileDetails";
import { ProfileEditForm } from "@src/components/profile-edit-form/ProfileEditForm";
import { ChatItem } from "@src/components/ui/chat-item/ChatItem";
import { ChatMessage } from "@src/components/ui/chat-message/ChatMessage";
import { DeleteButton } from "@src/components/ui/delete-button/DeleteButton";
import { Dropdown } from "@src/components/ui/dropdown/Dropdown";
import { FormField } from "@src/components/ui/form-field/FormField";
import { Input } from "@src/components/ui/input/Input";
import { InlineFormField } from "@src/components/ui/inline-form-field/InlineFormField";
import { Modal } from "@src/components/ui/modal/Modal";
import { SubmitButton } from "@src/components/ui/submit-button/SubmitButton";
import { UpdateChatAvatarForm } from "@src/components/update-chat-avatar-form/UpdateChatAvatarForm";

export function registerComponents() {
	registerComponent(AddUserToChatForm);
	registerComponent(AuthForm);
	registerComponent(AuthLayout);
	registerComponent(ChatItem);
	registerComponent(ChatMessage);
	registerComponent(CreateChatForm);
	registerComponent(DeleteButton);
	registerComponent(DialogHeader);
	registerComponent(DialogLayout);
	registerComponent(Dropdown);
	registerComponent(FormField);
	registerComponent(Input);
	registerComponent(InlineFormField);
	registerComponent(Modal);
	registerComponent(MessageForm);
	registerComponent(ProfileActions);
	registerComponent(ProfileAvatar);
	registerComponent(ProfileDetails);
	registerComponent(ProfileEditForm);
	registerComponent(ProfileLayout);
	registerComponent(RemoveUserFromChatForm);
	registerComponent(ServiceLayout);
	registerComponent(SidebarLayout);
	registerComponent(SubmitButton);
	registerComponent(UpdateChatAvatarForm);
}
